Vagrant.configure(2) do | config |
  config.ssh.insert_key = false
  config.ssh.username = 'vagrant'
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Ubuntu 14.04
  config.vm.define "ubuntu14" do |conf|
    conf.vm.hostname = "ubuntu14.dev"
    conf.vm.box = "ubuntu/trusty64"
    conf.vm.network :private_network, ip: "192.168.33.2"
    conf.vm.network "forwarded_port", guest: 4873, host: 4873
  end

  # CentOS 7
  config.vm.define "centos7" do |conf|
    conf.vm.hostname = "centos7.dev"
    conf.vm.box = "geerlingguy/centos7"
    conf.vm.network :private_network, ip: "192.168.33.3"
    conf.vm.network "forwarded_port", guest: 4873, host: 4874
  end

  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "sinopia_servers" => ["ubuntu14", "centos7"],
      "all_groups:children" => ["sinopia_servers"]
    }

    ansible.sudo = true
    ansible.playbook = "test.yml"
  end
end
